---
sudo: false
language: bash
cache:
  directories:
    - "${HOME}/google-cloud-sdk/"
    - "${HOME}/terraform/"
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin:${HOME}/terraform/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client-secret.json
before_install:
  - openssl aes-256-cbc -K $encrypted_8530b177f5a9_key -iv $encrypted_8530b177f5a9_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash; fi
  - tar -xzf credentials.tar.gz --directory $TRAVIS_BUILD_DIR
  - gcloud auth activate-service-account --key-file $TRAVIS_BUILD_DIR/client-secret.json
  - if [ ! -d "${HOME}/terraform/bin" ]; then curl -O https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip; mkdir ${HOME}/terraform/bin; unzip terraform_0.11.8_linux_amd64.zip -d ${HOME}/terraform/bin; fi
install:
  - gcloud -q components update
  - gcloud -q components install kubectl
script:
  - cd terraform
  - >-
    terraform init
    -backend-config="bucket=ops-iac-sb_tf_state"
    -backend-config="project=ops-iac-sb"
  - >-
    terraform workspace select ops-iac-sb-gocd ||
    terraform workspace new ops-iac-sb-gocd
  - >-
    terraform plan
    -out="plan.out"
    -var-file="travis.tfvars"
    -var="project=ops-gocd-$TRAVIS_BUILD_ID-sb"
    -var="host=gocd-$TRAVIS_BUILD_ID"
    -var="dns_project=ops-iac-sb"
    -var="billing_id=${billing_id}"
    -var="folder_id=${folder_id}"
