---
  kind: Service
  apiVersion: v1
  metadata:
    name: gocd-http
    namespace:  gocd
  spec:
    type: NodePort
    selector:
      app: gocd
    ports:
      - protocol: TCP
        port: 8153
        targetPort: 8153
        name: ui-http
      - protocol: TCP
        port: 8154
        targetPort: 8154
        name: agent
